# Вданном ноутбуке находятся расчеты тестирования МЕТА модели

In [1]:
from meta_model import load_meta_model

In [2]:
predictor = load_meta_model('full_meta_model.pth')

In [3]:
import numpy as np

print(f" Модель загружена")
print(f"   Классов: {len(predictor.diseases_list)}")
print(f"   Устройство: {predictor.device}")

# Пример использования
test_logits = np.random.randn(10, 45)  # 10 образцов
results = predictor.predict(test_logits)

print(f"\n Результаты:")
print(f"   Вероятности: {results['probabilities'].shape}")
print(f"   Предсказания: {results['binary_predictions'].shape}")

# Для одного образца
single_result = predictor.predict_single(test_logits[2])
print(f"\n Предсказания для одного снимка:")
print(f"   Заболевания: {single_result['predicted_diseases']}")

 Модель загружена
   Классов: 15
   Устройство: cuda

 Результаты:
   Вероятности: (10, 15)
   Предсказания: (10, 15)

 Предсказания для одного снимка:
   Заболевания: ['No Finding']


# тестируем полную сборку

# загружаем тестовую выборку

In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)  # Все колонки

In [2]:
test_data = pd.read_csv("3\\test_data.csv")

In [13]:
test_data

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11,full_path,Atelectasis,Cardiomegaly,Consolidation,Edema,Effusion,Emphysema,Fibrosis,Hernia,Infiltration,Mass,No Finding,Nodule,Pleural_Thickening,Pneumonia,Pneumothorax
0,00016028_000.png,No Finding,0,16028,52,M,PA,2500,2048,0.168000,0.168000,NaN,3\images_007\images\00016028_000.png,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,00014014_012.png,Pneumothorax,12,14014,20,F,PA,1650,1706,0.194311,0.194311,NaN,3\images_007\images\00014014_012.png,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,00004504_001.png,Effusion|Mass,1,4504,77,M,PA,2048,2500,0.171000,0.171000,NaN,3\images_003\images\00004504_001.png,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0
3,00011650_000.png,No Finding,0,11650,58,F,PA,2738,2533,0.143000,0.143000,NaN,3\images_006\images\00011650_000.png,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,00001875_003.png,Infiltration,3,1875,16,M,AP,2500,2048,0.168000,0.168000,NaN,3\images_002\images\00001875_003.png,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16813,00017489_000.png,No Finding,0,17489,53,M,PA,2586,2991,0.143000,0.143000,NaN,3\images_008\images\00017489_000.png,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
16814,00020773_009.png,Atelectasis|Effusion,9,20773,20,M,PA,2992,2991,0.143000,0.143000,NaN,3\images_009\images\00020773_009.png,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
16815,00028509_031.png,No Finding,31,28509,64,M,AP,3056,2544,0.139000,0.139000,NaN,3\images_012\images\00028509_031.png,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
16816,00029950_000.png,Infiltration,0,29950,36,F,PA,1624,2021,0.194311,0.194311,NaN,3\images_012\images\00029950_000.png,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0


In [14]:
dath_test = test_data['full_path']

In [15]:
dath_test

0        3\images_007\images\00016028_000.png
1        3\images_007\images\00014014_012.png
2        3\images_003\images\00004504_001.png
3        3\images_006\images\00011650_000.png
4        3\images_002\images\00001875_003.png
                         ...                 
16813    3\images_008\images\00017489_000.png
16814    3\images_009\images\00020773_009.png
16815    3\images_012\images\00028509_031.png
16816    3\images_012\images\00029950_000.png
16817    3\images_003\images\00005171_000.png
Name: full_path, Length: 16818, dtype: object

# импортируем модели

In [16]:
import DenseNet_model
#import EfficientNetV2_S_model
#import swin_tiny_model

In [17]:
logits_dn = DenseNet_model.get_logits_batch(dath_test)

Обработано 32/16818 изображений
Обработано 352/16818 изображений
Обработано 672/16818 изображений
Обработано 992/16818 изображений
Обработано 1312/16818 изображений
Обработано 1632/16818 изображений
Обработано 1952/16818 изображений
Обработано 2272/16818 изображений
Обработано 2592/16818 изображений
Обработано 2912/16818 изображений
Обработано 3232/16818 изображений
Обработано 3552/16818 изображений
Обработано 3872/16818 изображений
Обработано 4192/16818 изображений
Обработано 4512/16818 изображений
Обработано 4832/16818 изображений
Обработано 5152/16818 изображений
Обработано 5472/16818 изображений
Обработано 5792/16818 изображений
Обработано 6112/16818 изображений
Обработано 6432/16818 изображений
Обработано 6752/16818 изображений
Обработано 7072/16818 изображений
Обработано 7392/16818 изображений
Обработано 7712/16818 изображений
Обработано 8032/16818 изображений
Обработано 8352/16818 изображений
Обработано 8672/16818 изображений
Обработано 8992/16818 изображений
Обработано 9312/168

In [18]:
logits_dn.shape

(16818, 15)

In [19]:
import EfficientNetV2_S_model

C:\python\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\python\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


Модель загружена на cuda


In [20]:
logits_en = EfficientNetV2_S_model.get_logits_batch(dath_test)

In [21]:
logits_en.shape

(16818, 15)

In [22]:
import swin_tiny_model

Модель Swin-Tiny загружена на cuda
Размер изображения: 512x512
Val Loss: 0.00487007323999602


In [23]:
logits_st = swin_tiny_model.get_logits_batch(dath_test)

In [24]:
logits_st.shape

(16818, 15)

In [25]:
full_logits = np.concatenate((logits_dn, logits_en, logits_st), axis = 1)

In [43]:
full_logits.shape

(16818, 45)

In [58]:
full_logits

array([[-0.65707594, -1.2332808 , -1.0882325 , ..., -1.2744642 ,
        -1.5578644 , -1.6646936 ],
       [-0.52131397, -0.9316142 , -0.5072646 , ..., -0.49924105,
        -1.541422  , -0.3453353 ],
       [-0.42018196, -0.87815225, -0.8284517 , ..., -0.63506126,
        -0.8540624 , -1.0089898 ],
       ...,
       [-0.65094024, -0.8958204 , -0.3870449 , ..., -1.2329054 ,
        -1.112663  , -1.3159354 ],
       [-0.8925307 , -1.1557648 , -0.97718185, ..., -1.3169748 ,
        -1.6152595 , -1.5572547 ],
       [-0.8669516 , -1.2174491 , -1.0962877 , ..., -1.7914137 ,
        -2.11449   , -2.2217233 ]], dtype=float32)

# сохраним логиты тестовой выборки в csv файл

In [62]:
np.savetxt('full_test_logits1.csv', full_logits, delimiter=',', fmt='%.9f' )

# С этого момента можно начинать работу

# загружаем все логиты

In [1]:
import numpy as np
full_test_logits1 = np.loadtxt('full_test_logits1.csv', delimiter = ',')

In [2]:
full_test_logits1

array([[-0.65707594, -1.23328078, -1.08823252, ..., -1.27446425,
        -1.55786443, -1.66469359],
       [-0.52131397, -0.93161422, -0.50726461, ..., -0.49924105,
        -1.54142201, -0.3453353 ],
       [-0.42018196, -0.87815225, -0.82845169, ..., -0.63506126,
        -0.85406238, -1.00898981],
       ...,
       [-0.65094024, -0.89582038, -0.38704491, ..., -1.23290539,
        -1.11266303, -1.31593537],
       [-0.89253068, -1.15576482, -0.97718185, ..., -1.31697476,
        -1.61525953, -1.55725467],
       [-0.86695159, -1.21744907, -1.09628773, ..., -1.79141367,
        -2.11449003, -2.22172332]])

In [3]:
full_logits = full_test_logits1

In [4]:
from meta_model import load_meta_model

predictor = load_meta_model('full_meta_model.pth')

In [5]:
predictor.thresholds['Hernia'] = 0.005

In [6]:
predictor.thresholds

{'Atelectasis': 0.30000000000000004,
 'Cardiomegaly': 0.2,
 'Consolidation': 0.1,
 'Edema': 0.1,
 'Effusion': 0.30000000000000004,
 'Emphysema': 0.35000000000000003,
 'Fibrosis': 0.1,
 'Hernia': 0.005,
 'Infiltration': 0.30000000000000004,
 'Mass': 0.25,
 'No Finding': 0.4,
 'Nodule': 0.30000000000000004,
 'Pleural_Thickening': 0.1,
 'Pneumonia': 0.1,
 'Pneumothorax': 0.30000000000000004}

In [7]:
results = predictor.predict(full_logits)

In [8]:
results

{'probabilities': array([[1.85268279e-02, 2.83840607e-04, 2.75854324e-03, ...,
         2.40438767e-02, 1.78531732e-03, 7.85971875e-04],
        [8.45654458e-02, 2.67948164e-03, 2.09694710e-02, ...,
         1.11997351e-01, 2.17548991e-03, 4.99263018e-01],
        [2.50404954e-01, 1.94906086e-01, 1.04486205e-01, ...,
         1.34061471e-01, 4.03539315e-02, 5.86889982e-02],
        ...,
        [2.13366926e-01, 7.43344873e-02, 1.95706502e-01, ...,
         2.52466388e-02, 2.84636579e-02, 2.10576616e-02],
        [1.91741120e-02, 4.05472121e-04, 3.09018604e-02, ...,
         6.04463071e-02, 1.49920499e-02, 1.37057891e-02],
        [1.81977067e-03, 2.21915790e-04, 6.72836497e-04, ...,
         2.25088745e-03, 1.41695456e-03, 1.45976534e-04]], dtype=float32),
 'binary_predictions': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 1.],
        [0., 0., 1., ..., 1., 0., 0.],
        ...,
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
   

In [9]:
probabilities_meta = results['probabilities']

In [10]:
probabilities_meta

array([[1.85268279e-02, 2.83840607e-04, 2.75854324e-03, ...,
        2.40438767e-02, 1.78531732e-03, 7.85971875e-04],
       [8.45654458e-02, 2.67948164e-03, 2.09694710e-02, ...,
        1.11997351e-01, 2.17548991e-03, 4.99263018e-01],
       [2.50404954e-01, 1.94906086e-01, 1.04486205e-01, ...,
        1.34061471e-01, 4.03539315e-02, 5.86889982e-02],
       ...,
       [2.13366926e-01, 7.43344873e-02, 1.95706502e-01, ...,
        2.52466388e-02, 2.84636579e-02, 2.10576616e-02],
       [1.91741120e-02, 4.05472121e-04, 3.09018604e-02, ...,
        6.04463071e-02, 1.49920499e-02, 1.37057891e-02],
       [1.81977067e-03, 2.21915790e-04, 6.72836497e-04, ...,
        2.25088745e-03, 1.41695456e-03, 1.45976534e-04]], dtype=float32)

# истинные метки классов

In [11]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)  # Все колонки

test_data = pd.read_csv("3\\test_data.csv")

lables = np.array(test_data.iloc[:, -15:])

In [12]:
lables[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [13]:
lables.shape

(16818, 15)

# смотрим метрики качества

# вычисляем AUC

In [14]:
import numpy as np
from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt

# Вычисляем AUC для каждого класса
def calculate_class_auc(probabilities_meta, labels):
    """
    Вычисляет AUC для каждого класса отдельно
    """
    n_classes = probabilities_meta.shape[1]
    auc_per_class = []
    
    print("=== AUC по каждому классу ===")
    for i in range(n_classes):
        # Получаем вероятности и метки для текущего класса
        class_probs = probabilities_meta[:, i]
        class_labels = labels[:, i]
        
        # Проверяем, есть ли оба класса (0 и 1) в метках
        if len(np.unique(class_labels)) < 2:
            print(f"Класс {i}: AUC = N/A (все метки одинаковые)")
            auc_per_class.append(np.nan)
            continue
        
        try:
            # Вычисляем AUC для текущего класса
            auc = roc_auc_score(class_labels, class_probs)
            auc_per_class.append(auc)
            print(f"Класс {i}: AUC = {auc:.4f}")
        except Exception as e:
            print(f"Класс {i}: Ошибка при расчете AUC - {e}")
            auc_per_class.append(np.nan)
    
    return np.array(auc_per_class)

# Вычисляем общий AUC (macro-average и micro-average)
def calculate_overall_auc(probabilities_meta, labels):
    """
    Вычисляет общие метрики AUC
    """
    print("\n=== Общие метрики AUC ===")
    
    # 1. Macro-average AUC (среднее по классам)
    auc_per_class = calculate_class_auc(probabilities_meta, labels)
    valid_auc = auc_per_class[~np.isnan(auc_per_class)]
    
    if len(valid_auc) > 0:
        macro_auc = np.mean(valid_auc)
        print(f"\nMacro-average AUC: {macro_auc:.4f}")
    else:
        macro_auc = np.nan
        print("\nMacro-average AUC: N/A (нет валидных классов)")
    
    # 2. Micro-average AUC (объединяем все предсказания и метки)
    # Flatten все предсказания и метки
    micro_probs = probabilities_meta.ravel()
    micro_labels = labels.ravel()
    
    if len(np.unique(micro_labels)) >= 2:
        micro_auc = roc_auc_score(micro_labels, micro_probs)
        print(f"Micro-average AUC: {micro_auc:.4f}")
    else:
        micro_auc = np.nan
        print(f"Micro-average AUC: N/A (все метки одинаковые)")
    
    # 3. AUC по взвешенным классам (weighted average)
    if len(valid_auc) > 0:
        # Веса = доля положительных примеров в каждом классе
        class_weights = []
        valid_indices = np.where(~np.isnan(auc_per_class))[0]
        
        for idx in valid_indices:
            class_labels = labels[:, idx]
            weight = np.mean(class_labels)  # доля положительных примеров
            class_weights.append(weight)
        
        class_weights = np.array(class_weights)
        # Нормализуем веса
        if class_weights.sum() > 0:
            class_weights = class_weights / class_weights.sum()
            weighted_auc = np.sum(valid_auc * class_weights)
            print(f"Weighted-average AUC: {weighted_auc:.4f}")
        else:
            weighted_auc = np.nan
            print(f"Weighted-average AUC: N/A (все веса равны 0)")
    else:
        weighted_auc = np.nan
    
    return {
        'auc_per_class': auc_per_class,
        'macro_auc': macro_auc,
        'micro_auc': micro_auc,
        'weighted_auc': weighted_auc
    }

# Функция для визуализации ROC кривых
def plot_roc_curves_all(probabilities_meta, labels, auc_results):
    """
    Строит ROC кривые для каждого класса
    """
    n_classes = probabilities_meta.shape[1]
    
    # Определяем размер сетки для графиков
    n_cols = 4
    n_rows = int(np.ceil(n_classes / n_cols))
    
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(16, n_rows * 3.5))
    axes = axes.flatten() if n_classes > 1 else [axes]
    
    for i in range(n_classes):
        class_probs = probabilities_meta[:, i]
        class_labels = labels[:, i]
        
        # Проверяем, есть ли оба класса
        if len(np.unique(class_labels)) < 2:
            axes[i].text(0.5, 0.5, f'Class {i}\nOnly one class',
                        ha='center', va='center', fontsize=12)
            axes[i].set_title(f'Class {i}: AUC = N/A')
            axes[i].set_xlim([0, 1])
            axes[i].set_ylim([0, 1])
        else:
            # Вычисляем ROC кривую
            fpr, tpr, thresholds = roc_curve(class_labels, class_probs)
            auc_value = auc_results['auc_per_class'][i]
            
            # Строим ROC кривую
            axes[i].plot(fpr, tpr, 'b-', linewidth=2, label=f'AUC = {auc_value:.3f}')
            axes[i].plot([0, 1], [0, 1], 'r--', linewidth=1, label='Random')
            axes[i].set_title(f'Class {i}: AUC = {auc_value:.3f}')
            axes[i].set_xlabel('False Positive Rate')
            axes[i].set_ylabel('True Positive Rate')
            axes[i].legend(loc='lower right')
            axes[i].grid(True, alpha=0.3)
    
    # Скрываем лишние субплотов если есть
    for j in range(i + 1, len(axes)):
        axes[j].axis('off')
    
    plt.suptitle('ROC Curves for Each Class', fontsize=16, y=1.02)
    plt.tight_layout()
    plt.show()
    
    # Также строим общий график со всеми кривыми
    plt.figure(figsize=(10, 8))
    
    for i in range(n_classes):
        class_probs = probabilities_meta[:, i]
        class_labels = labels[:, i]
        
        if len(np.unique(class_labels)) >= 2:
            fpr, tpr, _ = roc_curve(class_labels, class_probs)
            auc_value = auc_results['auc_per_class'][i]
            plt.plot(fpr, tpr, lw=1.5, alpha=0.7, label=f'Class {i}: AUC = {auc_value:.3f}')
    
    plt.plot([0, 1], [0, 1], 'k--', lw=2, label='Random (AUC = 0.5)')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate', fontsize=12)
    plt.ylabel('True Positive Rate', fontsize=12)
    plt.title('All ROC Curves Together', fontsize=14)
    plt.legend(loc='lower right', fontsize=9)
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()

# Основная функция для расчета всех метрик
def calculate_all_auc_metrics(probabilities_meta, labels):
    """
    Основная функция для расчета всех AUC метрик
    """
    # Проверяем размерности
    assert probabilities_meta.shape == labels.shape, \
        f"Размерности не совпадают: probabilities_meta {probabilities_meta.shape}, labels {labels.shape}"
    
    print(f"Размерность probabilities_meta: {probabilities_meta.shape}")
    print(f"Размерность labels: {labels.shape}")
    print(f"Количество классов: {probabilities_meta.shape[1]}")
    
    # Вычисляем все AUC метрики
    auc_results = calculate_overall_auc(probabilities_meta, labels)
    
    # Выводим статистику по меткам
    print("\n=== Статистика по меткам ===")
    n_classes = labels.shape[1]
    for i in range(n_classes):
        class_labels = labels[:, i]
        pos_count = np.sum(class_labels == 1)
        neg_count = np.sum(class_labels == 0)
        pos_ratio = pos_count / len(class_labels)
        print(f"Класс {i}: {pos_count} положительных, {neg_count} отрицательных ({pos_ratio:.2%})")
    
    # Визуализируем ROC кривые
    plot_roc_curves_all(probabilities_meta, labels, auc_results)
    
    return auc_results

In [15]:
calculate_class_auc(probabilities_meta, lables)

=== AUC по каждому классу ===
Класс 0: AUC = 0.8180
Класс 1: AUC = 0.8911
Класс 2: AUC = 0.8110
Класс 3: AUC = 0.8985
Класс 4: AUC = 0.8829
Класс 5: AUC = 0.9409
Класс 6: AUC = 0.8112
Класс 7: AUC = 0.8692
Класс 8: AUC = 0.7226
Класс 9: AUC = 0.8460
Класс 10: AUC = 0.7848
Класс 11: AUC = 0.7880
Класс 12: AUC = 0.8166
Класс 13: AUC = 0.7450
Класс 14: AUC = 0.8969


array([0.81797472, 0.89107535, 0.81101338, 0.89848848, 0.88293963,
       0.94090392, 0.81118651, 0.86916107, 0.72259877, 0.84603635,
       0.78475953, 0.78800845, 0.81655939, 0.74501686, 0.89689917])

In [16]:
calculate_overall_auc(probabilities_meta, lables)


=== Общие метрики AUC ===
=== AUC по каждому классу ===
Класс 0: AUC = 0.8180
Класс 1: AUC = 0.8911
Класс 2: AUC = 0.8110
Класс 3: AUC = 0.8985
Класс 4: AUC = 0.8829
Класс 5: AUC = 0.9409
Класс 6: AUC = 0.8112
Класс 7: AUC = 0.8692
Класс 8: AUC = 0.7226
Класс 9: AUC = 0.8460
Класс 10: AUC = 0.7848
Класс 11: AUC = 0.7880
Класс 12: AUC = 0.8166
Класс 13: AUC = 0.7450
Класс 14: AUC = 0.8969

Macro-average AUC: 0.8348
Micro-average AUC: 0.9159
Weighted-average AUC: 0.8030


{'auc_per_class': array([0.81797472, 0.89107535, 0.81101338, 0.89848848, 0.88293963,
        0.94090392, 0.81118651, 0.86916107, 0.72259877, 0.84603635,
        0.78475953, 0.78800845, 0.81655939, 0.74501686, 0.89689917]),
 'macro_auc': 0.8348414392341598,
 'micro_auc': 0.9159048695919039,
 'weighted_auc': 0.803031814421816}

# вычисляем Precision, recall, F1-score

In [17]:
#lables # истинные метки
binary_predictions = results['binary_predictions']

In [18]:
labels = lables

In [19]:
binary_predictions.shape

(16818, 15)

In [20]:
diseases = results["diseases"]

In [21]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

# Расчет метрик для каждого класса
n_classes = labels.shape[1]
print("Метрики по каждому классу:")
print("-" * 60)

for i in range(n_classes):
    class_pred = binary_predictions[:, i]
    class_true = labels[:, i]
    
    # Если в классе нет положительных примеров
    if np.sum(class_true) == 0:
        print(f"{diseases[i]}: Нет положительных примеров в метках")
        continue
    
    # Метрики для текущего класса
    precision = precision_score(class_true, class_pred, zero_division=0)
    recall = recall_score(class_true, class_pred, zero_division=0)
    f1 = f1_score(class_true, class_pred, zero_division=0)
    
    print(f"{diseases[i]}:")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f}")
    print(f"  F1-score:  {f1:.4f}")

print("\nОбщие метрики:")
print("-" * 60)

# Micro-average
precision_micro = precision_score(labels, binary_predictions, average='micro', zero_division=0)
recall_micro = recall_score(labels, binary_predictions, average='micro', zero_division=0)
f1_micro = f1_score(labels, binary_predictions, average='micro', zero_division=0)

print(f"Micro-average:")
print(f"  Precision: {precision_micro:.4f}")
print(f"  Recall:    {recall_micro:.4f}")
print(f"  F1-score:  {f1_micro:.4f}")

# Macro-average
precision_macro = precision_score(labels, binary_predictions, average='macro', zero_division=0)
recall_macro = recall_score(labels, binary_predictions, average='macro', zero_division=0)
f1_macro = f1_score(labels, binary_predictions, average='macro', zero_division=0)

print(f"\nMacro-average:")
print(f"  Precision: {precision_macro:.4f}")
print(f"  Recall:    {recall_macro:.4f}")
print(f"  F1-score:  {f1_macro:.4f}")

# Weighted-average
precision_weighted = precision_score(labels, binary_predictions, average='weighted', zero_division=0)
recall_weighted = recall_score(labels, binary_predictions, average='weighted', zero_division=0)
f1_weighted = f1_score(labels, binary_predictions, average='weighted', zero_division=0)

print(f"\nWeighted-average:")
print(f"  Precision: {precision_weighted:.4f}")
print(f"  Recall:    {recall_weighted:.4f}")
print(f"  F1-score:  {f1_weighted:.4f}")

Метрики по каждому классу:
------------------------------------------------------------
Atelectasis:
  Precision: 0.4430
  Recall:    0.3109
  F1-score:  0.3654
Cardiomegaly:
  Precision: 0.3459
  Recall:    0.3603
  F1-score:  0.3529
Consolidation:
  Precision: 0.1295
  Recall:    0.5847
  F1-score:  0.2120
Edema:
  Precision: 0.1481
  Recall:    0.5634
  F1-score:  0.2345
Effusion:
  Precision: 0.5096
  Recall:    0.6109
  F1-score:  0.5557
Emphysema:
  Precision: 0.5118
  Recall:    0.4754
  F1-score:  0.4929
Fibrosis:
  Precision: 0.1234
  Recall:    0.2557
  F1-score:  0.1665
Hernia:
  Precision: 0.0095
  Recall:    0.6786
  F1-score:  0.0187
Infiltration:
  Precision: 0.4130
  Recall:    0.3998
  F1-score:  0.4063
Mass:
  Precision: 0.3824
  Recall:    0.3842
  F1-score:  0.3833
No Finding:
  Precision: 0.7039
  Recall:    0.8178
  F1-score:  0.7566
Nodule:
  Precision: 0.4530
  Recall:    0.1643
  F1-score:  0.2411
Pleural_Thickening:
  Precision: 0.1579
  Recall:    0.3909
  F1

In [9]:
import torch
import gc

# 1. Очистка кэша CUDA
torch.cuda.empty_cache()

# 2. Сборщик мусора Python
gc.collect()

# 3. Удаление конкретных переменных (если они есть)
if 'model' in locals():
    del model
if 'logits' in locals():
    del logits
if 'images' in locals():
    del images

# 4. Еще раз очистка
torch.cuda.empty_cache()
gc.collect()

# 5. Проверить свободную память
print(f"Свободно памяти на GPU: {torch.cuda.memory_allocated()/1e9:.2f} GB занято")
print(f"Всего свободно: {torch.cuda.memory_reserved()/1e9:.2f} GB зарезервировано")

Свободно памяти на GPU: 0.03 GB занято
Всего свободно: 0.05 GB зарезервировано


In [65]:
x =0.800                                                                                                                                                                                                                                                                                                                   
y = x + ((x/100)*2.2)
print(y)

0.8176


In [60]:
0.8282 + 0.9009   + 0.8191 + 0.9110  + 0.8986 + 0.9473  + 0.8261 + 0.8899 + 0.7570  + 0.8588 + 0.8044 + 0.7969 + 0.8302 + 0.7716 + 0.9100       

12.75

In [61]:
12.75 / 15

0.85

In [20]:
predictor.thresholds['Hernia'] = 0.001

{'Atelectasis': 0.30000000000000004,
 'Cardiomegaly': 0.2,
 'Consolidation': 0.1,
 'Edema': 0.1,
 'Effusion': 0.30000000000000004,
 'Emphysema': 0.35000000000000003,
 'Fibrosis': 0.1,
 'Hernia': 0.05,
 'Infiltration': 0.30000000000000004,
 'Mass': 0.25,
 'No Finding': 0.4,
 'Nodule': 0.30000000000000004,
 'Pleural_Thickening': 0.1,
 'Pneumonia': 0.1,
 'Pneumothorax': 0.30000000000000004}

In [22]:
predictor.thresholds

{'Atelectasis': 0.30000000000000004,
 'Cardiomegaly': 0.2,
 'Consolidation': 0.1,
 'Edema': 0.1,
 'Effusion': 0.30000000000000004,
 'Emphysema': 0.35000000000000003,
 'Fibrosis': 0.1,
 'Hernia': 0.001,
 'Infiltration': 0.30000000000000004,
 'Mass': 0.25,
 'No Finding': 0.4,
 'Nodule': 0.30000000000000004,
 'Pleural_Thickening': 0.1,
 'Pneumonia': 0.1,
 'Pneumothorax': 0.30000000000000004}

# Перерасчет порогов отсечения

# переасчет метрик качества

# загружаем все логиты тестовой выборки

In [1]:
import numpy as np
full_test_logits1 = np.loadtxt('full_test_logits1.csv', delimiter = ',')

full_test_logits1

array([[-0.65707594, -1.23328078, -1.08823252, ..., -1.27446425,
        -1.55786443, -1.66469359],
       [-0.52131397, -0.93161422, -0.50726461, ..., -0.49924105,
        -1.54142201, -0.3453353 ],
       [-0.42018196, -0.87815225, -0.82845169, ..., -0.63506126,
        -0.85406238, -1.00898981],
       ...,
       [-0.65094024, -0.89582038, -0.38704491, ..., -1.23290539,
        -1.11266303, -1.31593537],
       [-0.89253068, -1.15576482, -0.97718185, ..., -1.31697476,
        -1.61525953, -1.55725467],
       [-0.86695159, -1.21744907, -1.09628773, ..., -1.79141367,
        -2.11449003, -2.22172332]])

In [2]:
full_test_logits1.shape

(16818, 45)

# загружаем истинные метки классов тестовой выборки

In [3]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)  # Все колонки

test_data = pd.read_csv("3\\test_data.csv")

lables = np.array(test_data.iloc[:, -15:])

In [4]:
lables[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

# загружаем мета модель, и меняем пороги отсечения

In [5]:
from meta_model import load_meta_model

predictor = load_meta_model('full_meta_model.pth')

In [6]:
predictor.thresholds['Hernia'] = 0.0000000001

# прогоняем логиты через мета модель

In [7]:
results = predictor.predict(full_test_logits1)

In [8]:
results

{'probabilities': array([[1.85268279e-02, 2.83840607e-04, 2.75854324e-03, ...,
         2.40438767e-02, 1.78531732e-03, 7.85971875e-04],
        [8.45654458e-02, 2.67948164e-03, 2.09694710e-02, ...,
         1.11997351e-01, 2.17548991e-03, 4.99263018e-01],
        [2.50404954e-01, 1.94906086e-01, 1.04486205e-01, ...,
         1.34061471e-01, 4.03539315e-02, 5.86889982e-02],
        ...,
        [2.13366926e-01, 7.43344873e-02, 1.95706502e-01, ...,
         2.52466388e-02, 2.84636579e-02, 2.10576616e-02],
        [1.91741120e-02, 4.05472121e-04, 3.09018604e-02, ...,
         6.04463071e-02, 1.49920499e-02, 1.37057891e-02],
        [1.81977067e-03, 2.21915790e-04, 6.72836497e-04, ...,
         2.25088745e-03, 1.41695456e-03, 1.45976534e-04]], dtype=float32),
 'binary_predictions': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 1.],
        [0., 0., 1., ..., 1., 0., 0.],
        ...,
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
   

In [11]:
binary_predictions = results['binary_predictions']

In [12]:
binary_predictions.shape

(16818, 15)

# расчеты в ручную

In [13]:
hernia_real_true_predict_false = []

for i in range(16818):
    if lables[i][7] == 1 and binary_predictions[i][7] != 1:
        hernia_real_true_predict_false.append([binary_predictions[i], i])

In [14]:
hernia_real_true_predict_false

[]

In [15]:
len(hernia_real_true_predict_false)

0

In [16]:
probabiliti = results['probabilities']

In [17]:
probabiliti[851]

array([0.18333596, 0.04788738, 0.02853533, 0.0042169 , 0.07213603,
       0.03206699, 0.06717793, 0.03723751, 0.17180811, 0.03576843,
       0.4935187 , 0.0819044 , 0.05200815, 0.02214138, 0.00911734],
      dtype=float32)

In [18]:
binary_predictions[851]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
      dtype=float32)

In [19]:
lables[851]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)